[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[build-dependencies]
gl_generator = "0.14.0"
cfg_aliases = "0.2.1"

[dependencies]
glutin = "0.32.0"
winit = "0.30.0"
raw-window-handle = "0.6"
glutin-winit = "0.5.0"
